---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  namespace: growi
data:
  memlock: "true"
  javaopt: "-Xms256m -Xmx256m"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: growi
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch-pv
  namespace: growi
spec:
  storageClassName: slow
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteOnce
  claimRef:
    namespace: growi
    name: elasticsearch-pvc
  hostPath:
    path: /var/elasticsearch/data
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: growi-elasticsearch
  namespace: growi
spec:
  replicas: 1
  selector:
    matchLabels:
      role: elasticsearch
  serviceName: "elasticsearch"
  template:
    metadata:
      labels:
        role: elasticsearch
    spec:
      containers:
      - name: app-container
        image: mazrean/elasticsearch:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "256Mi"
        volumeMounts:
        - name: datadir
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: bootstrap.memory_lock
          valueFrom:
            configMapKeyRef:
              name: elasticsearch
              key: memlock
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: elasticsearch
              key: javaopt
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: elasticsearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: growi-elasticsearch
  namespace: growi
spec:
  type: LoadBalancer
  ports:
    - name: "elasticsearch-port"
      protocol: "TCP"
      port: 9200
      targetPort: 39200
  selector:
    role: elasticsearch