---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-config-pvc
  namespace: growi
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-config-pv
  namespace: growi
spec:
  storageClassName: slow
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteOnce
  claimRef:
    namespace: growi
    name: mongo-config-pvc
  hostPath:
    path: /var/mongo/configdata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-pvc
  namespace: growi
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-data-pv
  namespace: growi
spec:
  storageClassName: slow
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteOnce
  claimRef:
    namespace: growi
    name: mongo-data-pvc
  hostPath:
    path: /var/mongo/data
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: growi-mongodb
  namespace: growi
spec:
  replicas: 1
  selector:
    matchLabels:
      role: db
  serviceName: "mongodb"
  template:
    metadata:
      namespace: growi
      labels:
        role: db
    spec:
      containers:
      - name: mongodb-container
        image: mongo:3.6
        volumeMounts:
        - name: configdatadir
          mountPath: /data/configdb
        - name: datadir
          mountPath: /data/db
      volumes:
      - name: configdatadir
        persistentVolumeClaim:
          claimName: mongo-config-pvc
      - name: datadir
        persistentVolumeClaim:
          claimName: mongo-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: growi-mongodb
  namespace: growi
spec:
  type: ClusterIP
  ports:
    - name: "mongodb-port"
      protocol: "TCP"
      port: 27017
      targetPort: 27017
  selector:
    role: db